# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kitchen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kitchen.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rkitchen.proto\"L\n\x0cSaladRequest\x12(\n\x0f\x66rom_dictionary\x18\x01 \x01(\x0e\x32\x0f.FromDictionary\x12\x12\n\nsalad_size\x18\x02 \x01(\x05\"\x1d\n\rSaladResponse\x12\x0c\n\x04word\x18\x01 \x03(\t*%\n\x0e\x46romDictionary\x12\t\n\x05\x46\x41LSE\x10\x00\x12\x08\n\x04TRUE\x10\x01\x32\x36\n\x07Kitchen\x12+\n\nServeSalad\x12\r.SaladRequest\x1a\x0e.SaladResponseb\x06proto3'
)

_FROMDICTIONARY = _descriptor.EnumDescriptor(
  name='FromDictionary',
  full_name='FromDictionary',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FALSE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRUE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=126,
  serialized_end=163,
)
_sym_db.RegisterEnumDescriptor(_FROMDICTIONARY)

FromDictionary = enum_type_wrapper.EnumTypeWrapper(_FROMDICTIONARY)
FALSE = 0
TRUE = 1



_SALADREQUEST = _descriptor.Descriptor(
  name='SaladRequest',
  full_name='SaladRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_dictionary', full_name='SaladRequest.from_dictionary', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='salad_size', full_name='SaladRequest.salad_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=93,
)


_SALADRESPONSE = _descriptor.Descriptor(
  name='SaladResponse',
  full_name='SaladResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='SaladResponse.word', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=124,
)

_SALADREQUEST.fields_by_name['from_dictionary'].enum_type = _FROMDICTIONARY
DESCRIPTOR.message_types_by_name['SaladRequest'] = _SALADREQUEST
DESCRIPTOR.message_types_by_name['SaladResponse'] = _SALADRESPONSE
DESCRIPTOR.enum_types_by_name['FromDictionary'] = _FROMDICTIONARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaladRequest = _reflection.GeneratedProtocolMessageType('SaladRequest', (_message.Message,), {
  'DESCRIPTOR' : _SALADREQUEST,
  '__module__' : 'kitchen_pb2'
  # @@protoc_insertion_point(class_scope:SaladRequest)
  })
_sym_db.RegisterMessage(SaladRequest)

SaladResponse = _reflection.GeneratedProtocolMessageType('SaladResponse', (_message.Message,), {
  'DESCRIPTOR' : _SALADRESPONSE,
  '__module__' : 'kitchen_pb2'
  # @@protoc_insertion_point(class_scope:SaladResponse)
  })
_sym_db.RegisterMessage(SaladResponse)



_KITCHEN = _descriptor.ServiceDescriptor(
  name='Kitchen',
  full_name='Kitchen',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=165,
  serialized_end=219,
  methods=[
  _descriptor.MethodDescriptor(
    name='ServeSalad',
    full_name='Kitchen.ServeSalad',
    index=0,
    containing_service=None,
    input_type=_SALADREQUEST,
    output_type=_SALADRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KITCHEN)

DESCRIPTOR.services_by_name['Kitchen'] = _KITCHEN

# @@protoc_insertion_point(module_scope)
